version: "3.8"

services:
  wp:
    image: wordpress:6.8.0-php8.1-fpm
    container_name: wp
    volumes:
      - ./wp1:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wp1:/var/www/html
    depends_on:
      - wp

  db:
    image: mariadb:10.6
    container_name: db
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
    volumes:
      - ./wp1/db_data:/var/lib/mysql
