version: "3.8"

services:
  wp:
    image: wordpress:php8.1
    container_name: wp
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes
      # - .:/var/www/html
      - share-html:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
  db:
    image: mariadb:10.6
    container_name: db
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  share-html:
  db_data:
